name: Build and run with CMakePresets.json, no parameter matrix

on:
  push: 
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: bash
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - run: Linux, Ninja, Gnu, Debug

    - name: "CMake configure: Linux, Ninja, Gnu, Debug"
      run: cmake --preset Ninja-Gnu-Debug
      
    - name: "CMake build: Linux, Ninja, Gnu, Debug"
      run: cmake --build --preset Ninja-Gnu-Debug

    - name: "CMake run: Linux, Ninja, Gnu, Debug"
      run: cmake --build --preset Ninja-Gnu-Debug --target run

    - run: Linux, Ninja, Gnu, Release

    - name: "CMake configure: Linux, Ninja, Gnu, Release"
      run: cmake --preset Ninja-Gnu-Release
      
    - name: "CMake build: Linux, Ninja, Gnu, Release"
      run: cmake --build --preset Ninja-Gnu-Release

    - name: "CMake run: Linux, Ninja, Gnu, Release"
      run: cmake --build --preset Ninja-Gnu-Release --target run


  build-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: bash
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - run: MacOS, Ninja, Clang, Debug

    - name: "CMake configure: Linux, Ninja, Clang, Debug"
      run: cmake --preset Ninja-Clang-Debug
      
    - name: "CMake build: Linux, Ninja, Clang, Debug"
      run: cmake --build --preset Ninja-Clang-Debug

    - name: "CMake run: Linux, Ninja, Clang, Debug"
      run: cmake --build --preset Ninja-Clang-Debug --target run

    - run: MacOS, Ninja, Clang, Release

    - name: "CMake configure: Linux, Ninja, Clang, Release"
      run: cmake --preset Ninja-Clang-Release
      
    - name: "CMake build: Linux, Ninja, Clang, Release"
      run: cmake --build --preset Ninja-Clang-Release

    - name: "CMake run: Linux, Ninja, Clang, Release"
      run: cmake --build --preset Ninja-Clang-Release --target run


  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: bash
      run: | 
        echo cl
        cl
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - run: Windows, Ninja, Msvc, Debug

    - name: "CMake configure: Linux, Ninja, Msvc, Debug"
      run: cmake --preset Ninja-Msvc-Debug
      
    - name: "CMake build: Linux, Ninja, Msvc, Debug"
      run: cmake --build --preset Ninja-Msvc-Debug

    - name: "CMake run: Linux, Ninja, Msvc, Debug"
      run: cmake --build --preset Ninja-Msvc-Debug --target run

    - run: Windows, Ninja, Msvc, Release

    - name: "CMake configure: Linux, Ninja, Msvc, Release"
      run: cmake --preset Ninja-Msvc-Release
      
    - name: "CMake build: Linux, Ninja, Msvc, Release"
      run: cmake --build --preset Ninja-Msvc-Release

    - name: "CMake run: Linux, Ninja, Msvc, Release"
      run: cmake --build --preset Ninja-Msvc-Release --target run
